### ISSUE TITLE
not launching

### ISSUE THREAD

**Issue by jjcatulle** [xvrh/puppeteer-dart#107]
Every time I try to launch puppeteer, I'm getting the error below. 
My code ran fine on windows, recently change to macOS and been facing that error.

`[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ProcessException: Operation not permitted
  Command: .local-chromium/722234/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain about:blank --remote-debugging-port=0 --user-data-dir=/var/folders/1v/r0fgllgj15gb1sgpm0xxvgrw0000gn/T/com.example.accelerateIo/puppeteer_dev_profile-UiNyi0`

**Comment by xvrh** [comment]
Hi,
Thanks for the report.

Can you provide a bit more information:
- What Dart SDK are you using (version) and how did you install it? Is it Flutter or standalone SDK?
- Where is located your project? Is it under a user-editable directory (Documents, etc..)?

**Comment by jjcatulle** [comment]
I'm using dart 2.8.0 , I Was using it originally in flutter and i came across that error, I try using the standalone SDK and got the same error.

My project folder is located within a folder in my desktop folder.

**Comment by xvrh** [comment]
There is some code in the "downloader" code that tries to give the permission to the chromium executable: https://github.com/xvrh/puppeteer-dart/blob/master/lib/src/downloader.dart#L47
But maybe it is not enough with latest version of macOS.

What is the result of this command in the terminal from your project folder `ls -la .local-chromium/722234/chrome-mac/Chromium.app/Contents/MacOS`?

**Comment by jjcatulle** [comment]
ls: .local-chromium/722234/chrome-mac/Chromium.app/Contents/MacOS: No such file or directory

**Comment by jjcatulle** [comment]
I haven't found a solution on how to fix the problem, hopefully, It's updated or a workaround is found.

**Comment by xvrh** [comment]
> ls: .local-chromium/722234/chrome-mac/Chromium.app/Contents/MacOS: No such file or directory

So is there no folder at this location? Can you see the `.local-chromium/722234` directory?

Normally, when you run `puppeteer.launch` for the first time (and you don't specify an `executablePath`), it will download and unzip a copy of chromium at this location.
If you don't see the folder, something went wrong at that stage.

Maybe you can just try the "download" part in isolation like this: https://github.com/xvrh/puppeteer-dart/blob/master/example/download_chromium.dart

**Comment by vtisnado** [comment]
Hi guys, do yo found any working solution for this?

Im having the same issue when trying any of the examples in a Flutter Android app.

**Comment by xvrh** [comment]
@vtisnado unfortunately it's impossible to launch a chromium process in an Android app. Puppeteer only works on desktop/server OS (windows, macOS and linux).

**Comment by vtisnado** [comment]
Thank you for your soon answer @xvrh I think is confusing since the package shows that works with Flutter( Android / iOS) in pub.dev.

**Comment by jjcatulle** [comment]
Still can't seem to get around this issue, it got something to do with the permissions when downloading chromium. In the meantime, I'm just going to work on windows momentarily until this issue is fixed.

**Comment by SwissCheese5** [comment]
I'm getting this issue in my ubuntu container on Google cloud run
```
2020-06-14T19:32:22.125165ZProcessException: No such file or directory
2020-06-14T19:32:22.125189Z Command: unzip .local-chromium/737027_chrome-linux.zip -d .local-chromium/737027
2020-06-14T19:32:22.125892Z#0 _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
2020-06-14T19:32:22.125907Z#1 _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:640:18)
2020-06-14T19:32:22.125914Z#2 Process.runSync (dart:io-patch/process_patch.dart:68:12)
2020-06-14T19:32:22.125922Z#3 _unzip (package:puppeteer/src/downloader.dart:71:13)
2020-06-14T19:32:22.125930Z#4 downloadChrome (package:puppeteer/src/downloader.dart:38:5)
2020-06-14T19:32:22.125937Z<asynchronous suspension>
2020-06-14T19:32:22.125944Z#5 _inferExecutablePath (package:puppeteer/src/puppeteer.dart:330:19)
2020-06-14T19:32:22.125952Z#6 Puppeteer.launch (package:puppeteer/src/puppeteer.dart:140:30)
2020-06-14T19:32:22.125959Z<asynchronous suspension>
```

```
FROM ubuntu:18.04

ENV DART_VERSION=2.8.4
```

**Comment by SwissCheese5** [comment]
@xvrh Downloading the file directly from 
`https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/756035/chrome-linux.zip` yields the following file: 
![image](https://user-images.githubusercontent.com/7407478/85018012-1f248b00-b175-11ea-96b2-1e22e5c45ad7.png)
While puppeteer is assuming the file location to be:
```dart
    var zipPath = p.join(cachePath, '${revision}_${p.url.basename(url)}');
```
Which is `.local-chromium/737027_chrome-linux.zip`
specifically `737027_chrome-linux.zip`

I'm not sure if this is a change from chrome's storage bucket naming scheme or what, but you have a few options:

- Either rename the assumption
- Download the file into an empty temp folder, then get a list of all files in that directory (which will only ever be 1) and get the name that way (filesList[0])
- Use Dio which can rename the file for you https://pub.dev/packages/dio
 ```dart
response = await dio.download("https://www.google.com/", "./xx.html");
```

**Comment by xvrh** [comment]
@SwissCheese5 The `zipPath` is used as the destination file for the download at line 56 in this file.

Could you show your `Dockerfile` so we can take a look at it?

Generally when I want to use puppeteer in a Docker container, I pre-download chromium directly in a build step in the Dockerfile (ie `RUN dart download_chromium.dart`).

**Comment by SwissCheese5** [comment]
@xvrh I already tried doing
```dart
      var chromePath = await downloadChrome();
      print(chromePath.executablePath);
```
which returns the same result.
Here's my docker, but i doubt it's very relavant to the issue.
```Dockerfile
FROM ubuntu:18.04

ENV DART_VERSION=2.8.4

# gnupg2: https://stackoverflow.com/questions/50757647
RUN \
  apt-get -q update && apt-get install --no-install-recommends -y -q gnupg2 curl git ca-certificates apt-transport-https openssh-client && \
  curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
  curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list && \
  curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_testing.list > /etc/apt/sources.list.d/dart_testing.list && \
  curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_unstable.list > /etc/apt/sources.list.d/dart_unstable.list && \
  apt-get update && \
  apt-get install dart=$DART_VERSION-1 && \
  rm -rf /var/lib/apt/lists/*

ENV DART_SDK /usr/lib/dart
ENV PATH $DART_SDK/bin:/root/.pub-cache/bin:$PATH

ADD dart_run.sh /dart_runtime/
RUN chmod 755 /dart_runtime/dart_run.sh && \
  chown root:root /dart_runtime/dart_run.sh

ENV PORT 8080

# Expose ports for debugger (5858), application traffic ($PORT)
# and the observatory (8181)
EXPOSE $PORT 8181 5858

WORKDIR /app

# In docker each step creates an image layer that is cached. We add the
# pubspec.* before "pub get", then we add the rest of /app/ and run
# "pub get --offline". Thus, rebuilding without touching pubspec.* files won't
# download all dependencies again (facilitating faster image rebuilds).
ADD pubspec.* /app/
RUN pub get
ADD . /app/
RUN pub get --offline

RUN apt-get update
RUN apt-get -y install software-properties-common
RUN add-apt-repository ppa:chris-needham/ppa
RUN apt-get update
RUN apt-get -y install audiowaveform

CMD []
ENTRYPOINT ["/dart_runtime/dart_run.sh"]
```

**Comment by SwissCheese5** [comment]
I forked the project and did this:
```dart
Future _downloadFile(String url, String output) async {
  var outputFile = File(output);
  await outputFile.create(recursive: true);

  var client = http.Client();
  var response = await client.send(http.Request('get', Uri.parse(url)));
  await response.stream.pipe(outputFile.openWrite());
  client.close();

  if (!outputFile.existsSync() || outputFile.lengthSync() == 0) {
    throw Exception('File was not downloaded from $url to $output');
  }
}
```
And got the exact same results. Very odd.

**Comment by SwissCheese5** [comment]
Hmm, seems to work, but i did a number of changes, i think it's specifically this that fixed it:
```dockerfile
RUN apt-get -y install zip unzip
```

**Comment by SwissCheese5** [comment]
@xvrh Now I'm getting this error:
```
Exception: Websocket url not found
2020-06-24T17:31:28.533239Z#0 _waitForWebSocketUrl (package:puppeteer/src/puppeteer.dart:311:3)
2020-06-24T17:31:28.533249Z<asynchronous suspension>
2020-06-24T17:31:28.533259Z#1 Puppeteer.launch (package:puppeteer/src/puppeteer.dart:170:30)
2020-06-24T17:31:28.533266Z<asynchronous suspension>
```
Can you shed some line on this?

**Comment by timrijckaert** [comment]
Thanks for all the pointers @SwissCheese5.  
I have following Dockerfile that works with this lib

```Dockerfile
FROM google/dart:2.12
RUN  apt-get update \
    # Puppeteer will try and unzip the Chromium installation
    && apt-get install -y wget zip unzip gnupg ca-certificates \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    # We install Chrome to get all the OS level dependencies, but Chrome itself
    # is not actually used as it's packaged in the node puppeteer library.
    # Alternatively, we could could include the entire dep list ourselves
    # (https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix)
    # but that seems too easy to get out of date.
    && apt-get install -y google-chrome-stable \
    && rm -rf /var/lib/apt/lists/* \
    && wget --quiet https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -O /usr/sbin/wait-for-it.sh \
    && chmod +x /usr/sbin/wait-for-it.sh
```

**Comment by cinder92** [comment]
having same issue in MacOS Monterey and latest version of this package.

**Comment by rohitsangwan01** [comment]
> 
for MacOs try  to disable sandbox mode , comment this out in macos/Runner/*.entitlements:

```
<key>com.apple.security.app-sandbox</key>
<true/>
```

**Comment by ysyfff** [comment]
> > 
> 
> for MacOs try to disable sandbox mode , comment this out in macos/Runner/*.entitlements:
> 
> ```
> <key>com.apple.security.app-sandbox</key>
> <true/>
> ```

Correct!!! Thanks man
