### ISSUE TITLE
Evaluate Dart function

### ISSUE THREAD

**Issue by jodinathan** [xvrh/puppeteer-dart#122]
I need to access some dart functions with puppeteer but it can't understand the result from the evaluation:

```
Unhandled exception:
Evaluation failed: test
#0      ExecutionContext._evaluateInternal (package:puppeteer/src/page/execution_context.dart:171:11)
<asynchronous suspension>
#1      ExecutionContext.evaluate (package:puppeteer/src/page/execution_context.dart:77:26)
#2      DomWorld.evaluate (package:puppeteer/src/page/dom_world.dart:68:20)
<asynchronous suspension>
```

The page code is basically:

```
void main() async {
  setProperty(html.window, 'askSendVideoX', allowInterop((String a) async {
    await Future.delayed(Duration(seconds: 1));
    return 'test';
  }));
}
```

My evaluate call: 

```
await page.evaluate<String>('x => {return askSendVideoX(x);}', args: ['1']);
```

Why the evaluation fail?

**Comment by xvrh** [comment]
Hi,
I'm think one of the problem is the usage of `async` in your `askSendVideoX` function.

I was able to make it work with a workarround like this:

```dart
import 'dart:html';
import 'dart:js';

void main() {
  JsObject.fromBrowserObject(window)['askSendVideoX'] =
      allowInterop((String a, JsFunction callback) async {
    callback.apply(['test $a']);
  });
}
```

and an evaluation like:
```dart
  var response = await page.evaluate(
      'x => new Promise((resolve) => askSendVideoX(x, resolve))',
      args: ['1']);
```

Here is my full test script:
```dart
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;

import 'package:puppeteer/puppeteer.dart';

void main() async {
  var webdev = await Process.start(
      'webdev', ['serve', 'web:0', '--no-injected-client', '--no-debug'],
      runInShell: true);

  var urlCompleter = Completer<String>();

  var urlExtractor = RegExp(r'Serving `web` on (.*)$');

  var stdoutSubscription = webdev.stdout
      .transform(utf8.decoder)
      .transform(const LineSplitter())
      .listen((event) {
    var match = urlExtractor.firstMatch(event);
    if (match != null) {
      urlCompleter.complete(match.group(1));
    }
  });

  var url = await urlCompleter.future;

  var browser = await puppeteer.launch();
  var page = await browser.newPage();
  page.onConsole.listen((event) {
    print('Console $event');
  });

  var destination = p.url.join(url, 'dart_interop_example.html');
  await page.goto(destination, wait: Until.networkIdle);

  var response = await page.evaluate(
      'x => new Promise((resolve) => askSendVideoX(x, resolve))',
      args: ['1']);
  print('Response ${await response}');

  await browser.close();

  await stdoutSubscription.cancel();
  webdev.kill();
  await webdev.exitCode;
}
```

**Comment by jodinathan** [comment]
I would like to thank you for this very important package.
