### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by chadrickman** [xvrh/puppeteer-dart#139]
It looks like in the `js_handle.dart` we're casting a null object to non-null. Which leads to the error below.

Unhandled exception:
```bash
Null check operator used on a null value
#0      ElementHandle.$.<anonymous closure>
package:puppeteer/…/page/js_handle.dart:574
#1      _RootZone.runUnary (dart:async/zone.dart:1612:54)
#2      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#3      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#4      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#5      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#6      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:254:13)
#7      ElementHandle.$OrNull (package:puppeteer/src/page/js_handle.dart)
package:puppeteer/…/page/js_handle.dart:1
<asynchronous suspension>
```

**Comment by xvrh** [comment]
Hi, thanks for the report.
Do you have a small example to reproduce this error?

**Comment by chadrickman** [comment]
Yes! Here you go.

This is running on dart 2.12.1

```dart
void main() async {
  var browser = await puppeteer.launch();
  var myPage = await browser.newPage();

  await myPage.goto('https://dart.dev', wait: Until.networkIdle);

  // If you try to select for an element that isn't available it should return null
  // however the method returns a non-null response.
  await myPage.$('.dash-element-that-isnt-there');

  await browser.close();
}
```

**Comment by chadrickman** [comment]
As a temporary fix I wrapped the selector in a try/catch.

**Comment by xvrh** [comment]
ok, thanks.
The API has changed a bit with null-safety, there is a method `$OrNull` for cases where the element is not there.
```dart
  Future<ElementHandle> $(String selector);
  Future<ElementHandle?> $OrNull(String selector);
```

We can return to the old API if I have feedback that this is hard to use.

**Comment by chadrickman** [comment]
That makes perfect sense. I'm going to open a PR to add a comment that clarifies that distinction. I wouldn't have known to use that other call.
