### ISSUE TITLE
FormatException: Unknown 'android_arm64' from Platform.version '3.1.0 (stable) (Tue Aug 15 21:33:36 2023 +0000) on "android_arm64"'

### ISSUE THREAD

**Issue by goodboyx** [xvrh/puppeteer-dart#257]
I/flutter ( 2616): #0      new BrowserPlatform.fromDartPlatform.<anonymous closure> (package:puppeteer/src/downloader.dart:180:23)
I/flutter ( 2616): #1      ListBase.firstWhere (dart:collection/list.dart:131:38)
I/flutter ( 2616): #2      new BrowserPlatform.fromDartPlatform (package:puppeteer/src/downloader.dart:179:19)
I/flutter ( 2616): #3      BrowserPlatform.current (package:puppeteer/src/downloader.dart:186:23)
I/flutter ( 2616): #4      BrowserPlatform.current (package:puppeteer/src/downloader.dart)
I/flutter ( 2616): #5      downloadChrome (package:puppeteer/src/downloader.dart:38:32)
I/flutter ( 2616): #6      _inferExecutablePath (package:puppeteer/src/puppeteer.dart:357:19)
I/flutter ( 2616): #7      Puppeteer.launch (package:puppeteer/src/puppeteer.dart:153:30)
I/flutter ( 2616): <asynchronous suspension>
I/flutter ( 2616): #8      main (package:reservation/main.dart:5:19)
I/flutter ( 2616): <asynchronous suspension>
I/ion.reservatio( 2616): Compiler allocated 4MB to compile void android.view.ViewRootImpl.performTraversals()

**Comment by xvrh** [comment]
It is known that you cannot download and launch a chromium binary in Android. See the README: https://github.com/xvrh/puppeteer-dart#limitations-with-flutter
