### ISSUE TITLE
flutter android build failed

### ISSUE THREAD

**Issue by selvam920** [xvrh/puppeteer-dart#300]
Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Reference to package:puppeteer/protocol/css.dart::StyleSheetId is not bound to an AST node. An extension type declaration was expected

**Comment by selvam920** [comment]
anyone help me on this?

**Comment by xvrh** [comment]
Can you provide a small reproducible example?

**Comment by selvam920** [comment]
it's working, it was gradle 8.0 issue

**Comment by Akimskate** [comment]
Faced a similar problem, using gradle 8.3

```flutter build apk```

```Target aot_android_asset_bundle failed: IconTreeShakerException: ConstFinder failure: Unhandled exception:
Reference to package:puppeteer/protocol/css.dart::StyleSheetId is not bound to an AST node. An extension type declaration was expected
#0      Reference.asExtensionTypeDeclaration (package:kernel/canonical_name.dart:559:7)
#1      ExtensionType.extensionTypeDeclaration (package:kernel/ast.dart:11982:41)
#2      ExtensionType.visitChildren (package:kernel/ast.dart:12095:5)
#3      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#4      VisitorDefault.defaultDartType (package:kernel/visitor.dart:1524:39)
#5      DartTypeVisitorDefaultMixin.visitExtensionType (package:kernel/visitor.dart:804:47)
#6      ExtensionType.accept (package:kernel/ast.dart:12085:14)
#7      MapLiteral.visitChildren (package:kernel/ast.dart:8278:13)
#8      RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#9      VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#10     TreeVisitorDefault.defaultExpression (package:kernel/visitor.dart:618:43)
#11     ExpressionVisitorDefaultMixin.visitMapLiteral (package:kernel/visitor.dart:196:41)
#12     MapLiteral.accept (package:kernel/ast.dart:8270:44)
#13     VariableDeclaration.visitChildren (package:kernel/ast.dart:10749:18)
#14     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#15     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#16     TreeVisitorDefault.defaultStatement (package:kernel/visitor.dart:622:41)
#17     StatementVisitorDefaultMixin.visitVariableDeclaration (package:kernel/visitor.dart:386:7)
#18     VariableDeclaration.accept (package:kernel/ast.dart:10739:43)
#19     LocalInitializer.visitChildren (package:kernel/ast.dart:3597:14)
#20     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#21     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#22     TreeVisitorDefault.defaultInitializer (package:kernel/visitor.dart:624:45)
#23     InitializerVisitorDefaultMixin.visitLocalInitializer (package:kernel/visitor.dart:468:53)
#24     LocalInitializer.accept (package:kernel/ast.dart:3589:45)
#25     visitList (package:kernel/ast.dart:14784:14)
#26     Constructor.visitChildren (package:kernel/ast.dart:2685:5)
#27     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#28     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#29     TreeVisitorDefault.defaultMember (package:kernel/visitor.dart:626:35)
#30     MemberVisitorDefaultMixin.visitConstructor (package:kernel/visitor.dart:409:43)
#31     Constructor.accept (package:kernel/ast.dart:2671:40)
#32     visitList (package:kernel/ast.dart:14784:14)
#33     Class.visitChildren (package:kernel/ast.dart:1508:5)
#34     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:1725:10)
#35     VisitorDefault.defaultTreeNode (package:kernel/visitor.dart:1521:39)
#36     TreeVisitorDefaultMixin.visitClass (package:kernel/visitor.dart:556:31)
#37     _ConstVisitor.visitClass (package:kernel/const_finder.dart:132:11)
#38     Class.accept (package:kernel/ast.dart:1471:38)
#39     visitList (package:kernel/ast.dart:14784:14)
#40     Library.visitChildren (package:kernel/ast.dart:596:5)
#41     ConstFinder.findInstances (package:kernel/const_finder.dart:208:15)
#42     main (file:///b/s/w/ir/cache/builder/src/flutter/tools/const_finder/bin/main.dart:103:41)
#43     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#44     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)


To disable icon tree shaking, pass --no-tree-shake-icons to the requested flutter build command


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/home/akim/snap/flutter/common/flutter/bin/flutter'' finished with non-zero exit value 1
```

Error related to TreeShakeIcons.
we can pass 
```--no-tree-shake-icons```
 as a build argument - in that case build is OK, but is there any way to succsess build android apk without this argument?
