### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dheerajbred** [xvrh/puppeteer-dart#74]
I keep getting this error no matter which example I use

```
E/flutter (15583): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FileSystemException: Creation failed, path = '.local-chromium' (OS Error: Read-only file system, errno = 30)
E/flutter (15583): #0      _Directory.createSync (dart:io/directory_impl.dart:138:7)
E/flutter (15583): #1      _Directory.createSync (dart:io/directory_impl.dart:133:16)
E/flutter (15583): #2      downloadChrome (package:puppeteer/src/downloader.dart:27:23)
E/flutter (15583): <asynchronous suspension>
E/flutter (15583): #3      _inferExecutablePath (package:puppeteer/src/puppeteer.dart:282:19)
E/flutter (15583): <asynchronous suspension>
E/flutter (15583): #4      Puppeteer.launch (package:puppeteer/src/puppeteer.dart:108:28)
E/flutter (15583): <asynchronous suspension>
E/flutter (15583): #5      main (package:htmlparserexample/main.dart:4:33)
E/flutter (15583): <asynchronous suspension>
E/flutter (15583): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
E/flutter (15583): #7      _rootRun (dart:async/zone.dart:1124:13)
E/flutter (15583): #8      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (15583): #9      _runZoned (dart:async/zone.dart:1516:10)
E/flutter (15583): #10     runZoned (dart:async/zone.dart:1500:12)
E/flutter (15583): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
E/flutter (15583): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (15583): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (15583):

```

**Comment by xvrh** [comment]
You are seing an error because Puppeteer cannot download and write the Chromium binaries on your file system ("Read-only file system").

Maybe are you trying to run it on a mobile OS with Flutter? This is not supported. Puppeteer only works on a desktop computer (windows, macOS or linux).

Also it is preferable to use the full dart sdk (https://dart.dev/get-dart) instead of the sdk in Flutter.

**Comment by talhakhan1297** [comment]
If puppeteer is only usable for desktop than why it say it supports Android / iOS on pub.

![image](https://user-images.githubusercontent.com/50271102/100069624-cad7b280-2e5a-11eb-85d7-2fb379e25614.png)
