### ISSUE TITLE
Error on navigating a web page (maybe with frame)

### ISSUE THREAD

**Issue by YusukeIwaki** [xvrh/puppeteer-dart#90]
Reproduceable with the code below.

```
import 'package:puppeteer/puppeteer.dart';

main() async {
  final browser = await puppeteer.launch(
      headless: false,
      executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome');
  final Page page = await browser.newPage();
  await page.emulate(puppeteer.devices.iPhone8);
  await page.goto("https://www.jreast.co.jp/card/sp/servicelist/viewsnet/login.html");
  await page.click(".views_login .loginbtn");
}
```

```
Unhandled exception:
Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.
#0      List.forEach (dart:core-patch/growable_array.dart:284:36)
#1      FrameManager._onFrameNavigated (package:puppeteer/src/page/frame_manager.dart:194:25)
#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#5      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#6      _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
```

**Comment by xvrh** [comment]
I published the version `1.14.0` on pub.dev with the fix.
Thanks again
